type BlockInfo @entity {
  id: ID!
  hash: Bytes!
  blockNumber: BigInt!
  timestamp: BigInt!
}
type Reward @entity {
  "User's address+-+RewardReason"
  id: ID!
  "User's address"
  user: User!
  "reason"
  reason: RewardReason!
  "total reward amount"
  total: BigInt!
  "balance reward amount"
  balance: BigInt!
  "created at block information"
  createdAtBlockInfo: BlockInfo!
  createdAtBlockNumber: BigInt!
  "updated at block information"
  updatedAtBlockInfo: BlockInfo!
  updatedAtBlockNumber: BigInt!
}

enum RewardReason {
  TRANSACTION_FEE
  ORDER_REFERRER_FEE
  PLATFORM_REFERRER_FEE
  PROTOCOL_FEE
  OTHER
}

type User @entity {
  "User's address"
  id: ID!
  totalReward: BigInt!
  balanceReward: BigInt!
  "created at block information"
  createdAtBlockInfo: BlockInfo!
  createdAtBlockNumber: BigInt!
  "updated at block information"
  updatedAtBlockInfo: BlockInfo!
  updatedAtBlockNumber: BigInt!
  rewards: [Reward!]! @derivedFrom(field: "user")
  rewardDeposits: [RewardDeposit!]! @derivedFrom(field: "to")
  rewardWithdraws: [RewardWithdraw!]! @derivedFrom(field: "from")
}

type RewardDeposit @entity {
  "txHash+logIndex"
  id: ID!
  "txHash of the transaction"
  txHash: Bytes!
  "from"
  from: User!
  "to"
  to: User!
  "amount deposited"
  amount: BigInt!
  "reason"
  reason: RewardReason!
  "comment"
  comment: String
  "block number"
  blockNumber: BigInt!
  "block information"
  blockInfo: BlockInfo!
}

type RewardWithdraw @entity {
  "txHash"
  id: ID!
  "txHash of the transaction"
  txHash: Bytes!
  "block number"
  blockNumber: BigInt!
  "block information"
  blockInfo: BlockInfo!
  "from"
  from: User!
  "to"
  to: User!
  "amount withdrawn"
  amount: BigInt!
}

type Summary @entity {
  id: ID!
  totalPlatformReferrerFee: BigInt!
  totalOrderReferrerFee: BigInt!
  totalProtocolFee: BigInt!
  totalTransactionFee: BigInt!
  totalOtherFee: BigInt!
}
